/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/explore`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/layout`; params?: Router.UnknownInputParams; } | { pathname: `/page`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/canteen`; params?: Router.UnknownInputParams; } | { pathname: `/canteen/page`; params?: Router.UnknownInputParams; } | { pathname: `/canteen/tracker`; params?: Router.UnknownInputParams; } | { pathname: `/canteen/tracker/page`; params?: Router.UnknownInputParams; } | { pathname: `/merch`; params?: Router.UnknownInputParams; } | { pathname: `/merch/page`; params?: Router.UnknownInputParams; } | { pathname: `/print`; params?: Router.UnknownInputParams; } | { pathname: `/print/page`; params?: Router.UnknownInputParams; } | { pathname: `/print/ticket`; params?: Router.UnknownInputParams; } | { pathname: `/shuttle`; params?: Router.UnknownInputParams; } | { pathname: `/shuttle/page`; params?: Router.UnknownInputParams; } | { pathname: `/shuttle/ticket`; params?: Router.UnknownInputParams; } | { pathname: `/shuttle/ticket/page`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/layout`; params?: Router.UnknownOutputParams; } | { pathname: `/page`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/canteen`; params?: Router.UnknownOutputParams; } | { pathname: `/canteen/page`; params?: Router.UnknownOutputParams; } | { pathname: `/canteen/tracker`; params?: Router.UnknownOutputParams; } | { pathname: `/canteen/tracker/page`; params?: Router.UnknownOutputParams; } | { pathname: `/merch`; params?: Router.UnknownOutputParams; } | { pathname: `/merch/page`; params?: Router.UnknownOutputParams; } | { pathname: `/print`; params?: Router.UnknownOutputParams; } | { pathname: `/print/page`; params?: Router.UnknownOutputParams; } | { pathname: `/print/ticket`; params?: Router.UnknownOutputParams; } | { pathname: `/shuttle`; params?: Router.UnknownOutputParams; } | { pathname: `/shuttle/page`; params?: Router.UnknownOutputParams; } | { pathname: `/shuttle/ticket`; params?: Router.UnknownOutputParams; } | { pathname: `/shuttle/ticket/page`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/explore${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/layout${`?${string}` | `#${string}` | ''}` | `/page${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/canteen${`?${string}` | `#${string}` | ''}` | `/canteen/page${`?${string}` | `#${string}` | ''}` | `/canteen/tracker${`?${string}` | `#${string}` | ''}` | `/canteen/tracker/page${`?${string}` | `#${string}` | ''}` | `/merch${`?${string}` | `#${string}` | ''}` | `/merch/page${`?${string}` | `#${string}` | ''}` | `/print${`?${string}` | `#${string}` | ''}` | `/print/page${`?${string}` | `#${string}` | ''}` | `/print/ticket${`?${string}` | `#${string}` | ''}` | `/shuttle${`?${string}` | `#${string}` | ''}` | `/shuttle/page${`?${string}` | `#${string}` | ''}` | `/shuttle/ticket${`?${string}` | `#${string}` | ''}` | `/shuttle/ticket/page${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/explore`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/layout`; params?: Router.UnknownInputParams; } | { pathname: `/page`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/canteen`; params?: Router.UnknownInputParams; } | { pathname: `/canteen/page`; params?: Router.UnknownInputParams; } | { pathname: `/canteen/tracker`; params?: Router.UnknownInputParams; } | { pathname: `/canteen/tracker/page`; params?: Router.UnknownInputParams; } | { pathname: `/merch`; params?: Router.UnknownInputParams; } | { pathname: `/merch/page`; params?: Router.UnknownInputParams; } | { pathname: `/print`; params?: Router.UnknownInputParams; } | { pathname: `/print/page`; params?: Router.UnknownInputParams; } | { pathname: `/print/ticket`; params?: Router.UnknownInputParams; } | { pathname: `/shuttle`; params?: Router.UnknownInputParams; } | { pathname: `/shuttle/page`; params?: Router.UnknownInputParams; } | { pathname: `/shuttle/ticket`; params?: Router.UnknownInputParams; } | { pathname: `/shuttle/ticket/page`; params?: Router.UnknownInputParams; };
    }
  }
}
